#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
else
	mkdir /var/usb-server
	mkdir /var/usb-server/userinfo
	mv usb-connector /var/usb-server
	mv logout /var/usb-server/userinfo
	mv login /var/usb-server/userinfo
	mv mount /var/usb-server
	./changeconf
	./initdb
fi
