#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
else
	mkdir /var/userinfo
	mv logout /var/userinfo
	mv login /var/userinfo
	session-setup-script=/var/userinfo/declogin
	session-cleanup-script=/var/userinfo/declogout
	./initdb
fi
